
[manifest]
version = "1.3.0"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = "tag.lua"
pattern = """                    card = create_card('Joker', _context.area, nil, 1, nil, nil, nil, 'rta')"""
position = "at"
payload = """                    card = create_card('Joker', _context.area, nil, 1, nil, nil, nil, 'rta')
                    card.ability.eternal = nil; card.ability.perishable = nil; card.ability.rental = nil"""
match_indent = true

[[patches]]
[patches.pattern]
target = "tag.lua"
pattern = """                card = create_card('Joker', _context.area, nil, 0.9, nil, nil, nil, 'uta')"""
position = "at"
payload = """                card = create_card('Joker', _context.area, nil, 0.9, nil, nil, nil, 'uta')
                card.ability.eternal = nil; card.ability.perishable = nil; card.ability.rental = nil"""
match_indent = true


[[patches]]
[patches.pattern]
target = "tag.lua"
pattern = """                        _context.card:set_edition({foil = true}, true)"""
position = "at"
payload = """                        _context.card:set_edition({foil = true}, true)
                        _context.card.ability.eternal = nil; _context.card.ability.perishable = nil; _context.card.ability.rental = nil"""
match_indent = true


[[patches]]
[patches.pattern]
target = "tag.lua"
pattern = """                        _context.card:set_edition({holo = true}, true)"""
position = "at"
payload = """                        _context.card:set_edition({holo = true}, true)
                        _context.card.ability.eternal = nil; _context.card.ability.perishable = nil; _context.card.ability.rental = nil"""
match_indent = true


[[patches]]
[patches.pattern]
target = "tag.lua"
pattern = """                        _context.card:set_edition({polychrome = true}, true)"""
position = "at"
payload = """                        _context.card:set_edition({polychrome = true}, true)
                        _context.card.ability.eternal = nil; _context.card.ability.perishable = nil; _context.card.ability.rental = nil"""
match_indent = true


[[patches]]
[patches.pattern]
target = "tag.lua"
pattern = """                        _context.card:set_edition({negative = true}, true)"""
position = "at"
payload = """                        _context.card:set_edition({negative = true}, true)
                        _context.card.ability.eternal = nil; _context.card.ability.perishable = nil; _context.card.ability.rental = nil"""
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """                    {string = 'rand()', colour = G.C.JOKER_GREY},{string = "#@"..(G.deck and G.deck.cards[1] and G.deck.cards[#G.deck.cards].base.id or 11)..(G.deck and G.deck.cards[1] and G.deck.cards[#G.deck.cards].base.suit:sub(1,1) or 'D'), colour = G.C.RED},"""
position = "at"
payload = """                    {string = 'rand()', colour = G.C.JOKER_GREY},{string = "#@"..((self.area == G.jokers and G.deck and G.deck.cards[1]) and (G.deck.cards[#G.deck.cards].base.id..G.deck.cards[#G.deck.cards].base.suit:sub(1,1)) or '11D'), colour = G.C.RED},"""
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = """
G.hand.config.card_limits.blind_restriction = hand_space - math.min(#G.deck.cards, 3)
hand_space = math.min(#G.deck.cards, 3)
"""
position = "at"
payload = """
local num_cards = math.max(0, math.min(#G.deck.cards, 3, G.hand.config.card_limit - #G.hand.cards))
G.hand.config.card_limits.blind_restriction = hand_space - num_cards
hand_space = num_cards"""
match_indent = true

[[patches]]
[patches.pattern]
target = "UI_definitions.lua"
pattern = """{n=G.UIT.T, config={text = string.rep(localize("$"), blind_choice.config.dollars)..'+', scale = 0.35, colour = disabled and G.C.UI.TEXT_INACTIVE or G.C.MONEY, shadow = not disabled}}"""
position = "at"
payload = """
{n=G.UIT.T, config={text = string.rep(localize("$"), math.max(0, blind_choice.config.dollars - ((G.GAME.stake or 1) >= 2 and 1 or 0)))..'+', scale = 0.35, colour = disabled and G.C.UI.TEXT_INACTIVE or G.C.MONEY, shadow = not disabled}}
"""
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "update_hand_text({sound = 'button', volume = 0.7, pitch = 0.9, delay = 0}, {level='+1'})"
position = "at"
payload = "update_hand_text({sound = 'button', volume = 0.7, pitch = 0.9, delay = 0}, {level='+3'})"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "level_up_hand(self, k, true)"
position = "at"
payload = "level_up_hand(self, k, true, 3)"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "ease_dollars(-G.GAME.dollars, true)"
position = "at"
payload = "ease_dollars(-math.floor(math.max(0, G.GAME.dollars) / 2), true)"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = """            for j = 1, #G.jokers.cards do
                local eval = nil
                eval = G.jokers.cards[j]:calculate_joker({discard = true, other_card =  G.hand.highlighted[i], full_hand = G.hand.highlighted})
                if eval then
                    if eval.remove then removed = true end
                    card_eval_status_text(G.jokers.cards[j], 'jokers', nil, 1, nil, eval)
                end
            end"""
position = "at"
payload = """
            local allowed_jokers = {['Yorick'] = true, ['Hit the Road'] = true, ['Ramen'] = true, ['Castle'] = true, ['Mail-In Rebate'] = true}
            local has_allowed = false
            if G.jokers and G.jokers.cards then
                for _, jk in ipairs(G.jokers.cards) do
                    if allowed_jokers[jk.ability.name] then
                        has_allowed = true
                        break
                    end
                end
            end
            local reps = 1 + ((has_allowed and G.hand.highlighted[i]:get_seal() == 'Red') and 1 or 0)
            for r = 1, reps do
                if r > 1 then
                    card_eval_status_text(G.hand.highlighted[i], 'extra', nil, nil, nil, {message = localize('k_again_ex')})
                end
                for j = 1, #G.jokers.cards do
                    if r == 1 or allowed_jokers[G.jokers.cards[j].ability.name] then
                        local eval = nil
                        eval = G.jokers.cards[j]:calculate_joker({discard = true, other_card =  G.hand.highlighted[i], full_hand = G.hand.highlighted})
                        if eval then
                            if eval.remove then removed = true end
                            card_eval_status_text(G.jokers.cards[j], 'jokers', nil, 1, nil, eval)
                        end
                    end
                end
            end
"""
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """            delay(0.5)
            ease_dollars(self.ability.extra.dollars)"""
position = "before"
payload = """
            if G.jokers and G.jokers.cards then
                local destructable_jokers = {}
                for i = 1, #G.jokers.cards do
                    if G.jokers.cards[i] ~= self and not G.jokers.cards[i].ability.eternal and not G.jokers.cards[i].getting_sliced then 
                        destructable_jokers[#destructable_jokers+1] = G.jokers.cards[i] 
                    end
                end
                local joker_to_destroy = #destructable_jokers > 0 and pseudorandom_element(destructable_jokers, pseudoseed('immolate_joker')) or nil

                if joker_to_destroy then 
                    G.E_MANAGER:add_event(Event({
                        trigger = 'after',
                        delay = 0.4,
                        func = function()
                            joker_to_destroy:start_dissolve(nil, nil)
                            return true
                        end
                    }))
                end
            end
"""
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
        card_eval_status_text(self, 'extra', nil, nil, nil, {message = localize('k_plus_planet'), colour = G.C.SECONDARY_SET.Planet})
'''
position = "at"
payload = '''
        self.ability.blue_seal_triggers = (self.ability.blue_seal_triggers or 0) + 1
        local msg = localize('k_plus_planet')
        if self.ability.blue_seal_triggers >= 3 then
            msg = "Scraped!"
            G.E_MANAGER:add_event(Event({
                trigger = 'after',
                delay = 0.1,
                func = function()
                    self:set_seal(nil, true)
                    return true
                end
            }))
        end
        card_eval_status_text(self, 'extra', nil, nil, nil, {message = msg, colour = G.C.SECONDARY_SET.Planet})
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
            ease_discard(-1)
'''
position = "after"
payload = '''
            if G.GAME.blind.name == 'Amber Acorn' and #G.jokers.cards > 1 then
                G.E_MANAGER:add_event(Event({ trigger = 'after', delay = 0.2, func = function() 
                    G.E_MANAGER:add_event(Event({ func = function() G.jokers:shuffle('aajk'); play_sound('cardSlide1', 0.85);return true end })) 
                    delay(0.15)
                    G.E_MANAGER:add_event(Event({ func = function() G.jokers:shuffle('aajk'); play_sound('cardSlide1', 1.15);return true end })) 
                    delay(0.15)
                    G.E_MANAGER:add_event(Event({ func = function() G.jokers:shuffle('aajk'); play_sound('cardSlide1', 1);return true end })) 
                    delay(0.5)
                return true end })) 
            end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if G.GAME.used_vouchers.v_observatory and self.ability.consumeable.hand_type == context.scoring_name then"
position = "at"
payload = "if false and G.GAME.used_vouchers.v_observatory and self.ability.consumeable.hand_type == context.scoring_name then"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "level_up_hand(used_tarot, self.ability.consumeable.hand_type)"
position = "at"
payload = '''
        local lvl_amt = 1
        if G.GAME.used_vouchers.v_observatory then lvl_amt = 2 end
        level_up_hand(used_tarot, self.ability.consumeable.hand_type, nil, lvl_amt)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = '''
            for i = 1, 2 do
                if G.hand.cards[i] then 
                    local selected_card, card_key = pseudorandom_element(_cards, pseudoseed('hook'))
'''
position = "at"
payload = '''
            for i = 1, 3 do
                if G.hand.cards[i] then 
                    local selected_card, card_key = pseudorandom_element(_cards, pseudoseed('hook'))
'''
match_indent = true